export { default as popeFrancis2x } from './pope-francis.@2x.png'
export { default as popeFrancis } from './pope-francis.png'
export { default as search } from './search.svg'
export { default as thumbsDown } from './thumbs-down.svg'
export { default as thumbsUp } from './thumbs-up.svg'
